### PR TITLE
fix(docs): capitalize symbol

### PR DESCRIPTION
**Pull request by negezor**

### CODE REVIEW

**Comment by jimmywarting** [comment]
Ty

**Comment by jimmywarting** [comment]
@negezor Just curious what made you jump the train to formdata-node

**Comment by negezor** [comment]
@jimmywarting  Just having CommonJS 😄

**Comment by jimmywarting** [comment]
Ah, ok i see. 
Just FYI, formdata-node is going to switch to ESM in v4

(just b/c fetch-blob ditched commonjs and node-fetch is about to do it as well) 

You should switch to ESM also ;)

**Comment by jimmywarting** [comment]
i haven't tried form-data-encoder but i think it's compatible with my formdata version as well.

**Comment by negezor** [comment]
I'm in favor of using ESM, but I cannot transfer everything to ESM at once. I need a gradual migration for end developers.

**Pull request merged**
