### PR TITLE
fix linefeed handling for forms

### PR DESCRIPTION
**Pull request by visualjerk**
As the native FormData implementation converts linefeeds (LF) provided through user input to CRLF, the polyfill should do the same.

### CODE REVIEW

**Comment by jimmywarting** [comment]
Excellent PR. covered everything.

But i started to wonder whether or not this belonged more to the part when the body for multipart/form-data is generated. More precisely in this part:

https://github.com/jimmywarting/FormData/blob/f18bd6e8dbea9e520cdd0d98f539c520a236cee0/FormData.js#L296-L320 

i tested one of your test in the developer tool in firefox and safari also
```js
         const form = document.createElement('form')
         const textarea = document.createElement('textarea')
         textarea.name = 'key'
         textarea.value = '\n'
         form.appendChild(textarea)
         const fd = new FormData(form)
         const value = fd.get('key')
         console.log('\r\n' === value)
```

Both browser yield false but chrome yields true. So I'm now wondering what the correct behaviour should be

**Comment by jimmywarting** [comment]
this may be relevant: https://tools.ietf.org/html/rfc7578#section-4.1

**Comment by visualjerk** [comment]
That is a pretty weird issue. I am pretty sure that it has to be done inside the constructor, because setting the value through append results in Chrome keeping the single linefeed:

```js
const fd = new FormData()
fd.append('key', '\n')
console.log('\n' === fd.get('key')) // true in Chrome
```

That said, we still need to figure out which behavior is actually expected, when a form element is passed to the FormData constructor.

I try to find out more about this topic.

**Comment by visualjerk** [comment]
I created a bug report for chromium in order to shed light on this issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=917078

Let's see how this turns out.

**Comment by visualjerk** [comment]
Alright, it looks like Chrome is the only browser following the official HTML spec for textarea data normalization: https://html.spec.whatwg.org/multipage/form-elements.html#textarea-line-break-normalisation-transformation

That means we should include this normalization in the polyfill, but also restrict it to textarea inputs.

I adapt the merge request accordingly.

**Comment by jimmywarting** [comment]
Will publish it to npm when i get home to my personal computer.

**Pull request merged**
